# Generated by Django 5.0.3 on 2024-05-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'happy_customers',
            },
        ),
    ]
